services:
  lateststable:
    build: .
    container_name: lateststable
    restart: unless-stopped
    environment:
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lateststable.rule=Host(`lateststable.org`) || Host(`www.lateststable.org`)"
      - "traefik.http.routers.lateststable.entrypoints=websecure"
      - "traefik.http.routers.lateststable.tls.certresolver=myresolver"
      - "traefik.http.services.lateststable.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true
