from lst import LatestStable

lst = LatestStable()

# print(lst.pypi('pycalver'))
# print(lst.pypi('requests'))
# print(lst.jetbrains('IIU'))
# print(lst.jetbrains('pycharm'))
# print(lst.github('hashicorp/terraform'))
# print(lst.github('kubernetes/ingress-nginx'))
# print(lst.github('kubernetes/kubernetes'))
# # print(lst.github('derailed/k9s'))
# print(lst.docker('rdeknijf/strigoi'))
# print(lst.docker('python'))
# print(lst.docker('abiosoft/caddy'))
# print(lst.docker('scrapinghub/splash'))
#
# # print(lst.anywhere('k9s'))
# # print(lst.anywhere('jenkins'))
# print(lst.wikipedia('jenkins'))
# print(lst.wikipedia('Linux_kernel'))
# print(lst.wikipedia('Linux'))
# print(lst.wikipedia('Anjuta'))
# print(lst.wikipedia('Facebook_Messenger'))
# print(lst.wikipedia('Windows_NT'))
# print(lst.github('terraform-providers/terraform-provider-google'))
print(lst.npm('axios'))
