name: Build lasteststable

on: push

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_SA_KEY }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eu.gcr.io/lateststable/lateststable:latest
          cache-from: type=registry,ref=eu.gcr.io/lateststable/lateststable:latest
          cache-to: type=inline
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SA_KEY }}
          project_id: lateststable
          export_default_credentials: true
      - name: Deploy
        run: |-
          gcloud run deploy lateststable \
            --quiet \
            --region=europe-west4 \
            --image=eu.gcr.io/lateststable/lateststable:latest \
            --platform=managed \
            --allow-unauthenticated
