name: Build lasteststable

on: push

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SA_KEY }}
          project_id: lateststable
          export_default_credentials: true
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          registry: eu.gcr.io
          tags: lateststable/lateststable:latest
